FROM ppc64le/java:7-jdk

RUN apt-get update && apt-get install -y \
    build-essential \
    cpio \
    file \
    jq \
    libasound2-dev \
    libcups2-dev \
    libfreetype6-dev \
    libxext-dev \
    libxrender-dev \
    libxt-dev \
    libxtst-dev \
    mercurial \
    python-pip \
    zip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip install awscli --ignore-installed six

ADD ./openjdk.sh openjdk.sh
ADD ./common.sh common.sh
RUN  ARCH=ppc64le PLATFORM=trusty BUILD_NUMBER=b13 TAG=jdk8u101-b13  UPDATE_VERSION=101 UPLOAD_VERSION=1.8.0_101 ./openjdk.sh
